name: Release

on:
    workflow_dispatch:
        inputs:
            version_note:
                description: "Optional release note"
                type: string
                required: false

jobs:
    build:
        name: Build and upload release artifacts
        uses: ./.github/workflows/build.yml
        with:
            build_neoforge: true
            build_fabric: true
            upload_artifact: true
            retention_days: 7
